# Generated by Django 5.0.3 on 2024-04-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Student/Images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Student/CV/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('roll', models.IntegerField()),
                ('subject', models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('psychology', 'Psychology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology '), ('botany', 'Botany'), ('anatomy', 'Anatomy'), ('geology', 'Geology')], max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
