# Generated by Django 5.0.3 on 2024-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('subject', models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('psychology', 'Psychology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology '), ('botany', 'Botany'), ('anatomy', 'Anatomy'), ('geology', 'Geology')], max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Student/Images/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='Student/CV/')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
